### ISSUE TITLE
Issues with v5.0.0-beta2

### ISSUE THREAD

**Issue by neg** [dallaslu/bootstrap-5-multi-level-dropdown#1]
Hi,

Thanks for this nice code. Unfortunately it shows issues on v5.0.0-beta1 
and v5.0.0-beta2. If I modify your demo/fiddle to use either of the two 
beta releases the dropdown from the navbar "Documents" tab stack on-top 
of etch other instead of folding out to the left as it does with 
alpha{1,2,3}. Both buttons works as expected however.

**Comment by dallaslu** [comment]
Use class `dropend` instead of `dropright`.

**Comment by dallaslu** [comment]
The beta2 version seems to have changed the way it is implemented, so it seems to need some reworking.

**Comment by dallaslu** [comment]
Solved.

**Comment by neg** [comment]
Thanks, works perfectly for me.
