### ISSUE TITLE
Error on Hover

### ISSUE THREAD

**Issue by julienrondeau** [dallaslu/bootstrap-5-multi-level-dropdown#17]
in the demo.html (even in my own page) when hovering a navbar element or the buton hover, there is a js error in the console 

`dropdown.js:356 Uncaught TypeError: Cannot read properties of undefined (reading 'button')
    at Mt.clearMenus (dropdown.js:356:15)
    at HTMLDivElement.<anonymous> (bootstrap5-dropdown-ml-hack.js:33:30)`

any idea how to solve it ?

**Comment by dallaslu** [comment]
The [example](https://jsfiddle.net/dallaslu/mvk4uhzL/) works well. What is version of bootstrap in your case?

**Comment by julienrondeau** [comment]
In the package.json it is mentionned Bootstrap 5.0.2
but after npm install or yarn, Bootstrap 5.2.3 is installed.

the error is only on the hover button see below :

In Chrome 
<img width="1024" alt="chrome-issue" src="https://user-images.githubusercontent.com/9592059/217832201-35be942d-5bf5-4017-9308-f5d449772bb9.png">

in Firefox
<img width="715" alt="firefox-issue" src="https://user-images.githubusercontent.com/9592059/217832288-c56507e5-cdac-4923-b78f-e5c96347591f.png">

Any idea ?

thanks for the script anyway ;)

**Comment by dallaslu** [comment]
After reading the source code of dropdown.js, maybe this could work:

```diff
-$bs.Dropdown.clearMenus();
+$bs.Dropdown.clearMenus(e);
```

**Comment by julienrondeau** [comment]
Yes it works.

Thanks a lot!
