### ISSUE TITLE
Not working with dynamically generated multi-level-dropdowns

### ISSUE THREAD

**Issue by nepomuc** [dallaslu/bootstrap-5-multi-level-dropdown#7]
When generating the DOM structure of a multi-level-dropdown with JavaScript, it doesn't work properly. Only the first two levels will open, but not a third one. Also collapsing the second level back by clicking on the first layer entry doesn't work as well.
I'm not sure whether this should work, because it kind of does, but not properly.

Thanks for maybe fixing or enhancing the script in advance!

**Comment by dallaslu** [comment]
[bootstrap-4-multi-level-dropdown#2](https://github.com/dallaslu/bootstrap-4-multi-level-dropdown/issues/2#issuecomment-633918967)
